version: "3.8"
services:
    backend:
        build: .
        environment: 
            NODE_ENV: development
        depends_on:
        ports:
            - "3002:3002"
        networks:
            - default